apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-03-02T19:18:26Z"
  generation: 1
  labels:
    app: binarycalculator-deployment
  name: binarycalculator-deployment
  namespace: default
  resourceVersion: "4756886"
  uid: d6ed11d4-97a4-4b6d-bfdf-419b84a3a4dc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: binarycalculator-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: binarycalculator-deployment
    spec:
      containers:
      - image: northamerica-northeast2-docker.pkg.dev/utopian-river-452019-s9/sofe3980u/binarycalculator
        imagePullPolicy: Always
        name: binarycalculator
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-03-02T19:18:30Z"
    lastUpdateTime: "2025-03-02T19:18:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-02T19:18:26Z"
    lastUpdateTime: "2025-03-02T19:18:30Z"
    message: ReplicaSet "binarycalculator-deployment-6f968579b4" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
